# Turn on mouse
set -g mouse on 

set -g command-alias[100] "kill-session-safe=confirm-before -p 'Kill #S (y/n)?' 'run-shell \"if [ \\\"$(tmux list-sessions | wc -l)\\\" -gt 1 ]; then tmux switch-client -n; fi; tmux kill-session -t \\\"#S\\\"\"'"
set -g command-alias[101] "view-capture-pane=run-shell '~/bin/view-capture-pane.sh'"


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g detach-on-destroy off
set -g pane-border-format "#{pane_index} #{pane_title}"


bind -n MouseDown3Pane display-menu -T "Right-Click Menu" -x M -y M \
  "Horizontal Split" h "split-window -h" \
  "Vertical Split"  v "split-window -v" \
  "Kill Pane"       k "kill-pane" \
  "Kill Session"    X "kill-session-safe" \
  "Reload Config"   R "source-file ~/.tmux.conf"



# switch panes using Alt-arrow without prefix
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Display pane names
set -g pane-border-format "#{pane_index} #{pane_title}"
set -g pane-border-status bottom

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexwforsythe/tmux-which-key'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi

bind-key -Troot '`' show-wk-menu-root
set-hook -g client-resized 'run-shell "~/.tmux/scripts/tmux-resize-handler.sh"'
set-hook -g client-session-changed 'run-shell "~/.tmux/scripts/tmux-resize-handler.sh"'
set-hook -g client-attached 'run-shell "~/.tmux/scripts/tmux-resize-handler.sh"'

# capture-pane -e -J -p -S - > /tmp/tmux_capture.txt | tmux display-popup -h 100% -w 100% -E 'vim -c "set scrollback=100000" -c ":term cat /tmp/tmux_capture.txt" -c "set number" -c "set relativenumber" -c "\$"'

bind-key v run-shell "~/.tmux/scripts/view-capture-pane.sh" 
